name: Pruebas E2E con Cypress de mi aplicación

#cuando se ejecuta
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

#que se ejecuta
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-actions@v6
        with:
          build: npm run build
          start: npm run serve

          wait-on: "http://localhost:3000"
          browser: chrome

          command: npx cypress run baseUrl=http://localhost:3000
